### ISSUE TITLE
Sidebar for map load

### ISSUE THREAD

**Issue by jenmstrick** [USFWS/southeast-mega-map#17] opened 2016-08-02 20:06 UTC
Place USFWS shield top, center. Beneath, map title. "U.S. Fish and Wildlife Service, Southeast Region Office Map" or whatever you like. Even Mega Map!

Beneath that, include these instructions on how to use the map (I figured I'd let you take a shot at this first and I can come in to help if you want!): 
- Images of the icons from the map, e.g. toggle layers, find nearest offices, etc. with what they are and list the different layers that can be toggled on/off here. 
- Explain what the different station icons mean, and that users can click those icons to get information on that station.

**Comment by rhewitt22** [comment] 2016-08-02 20:14
@jenmstrick Good thinking -- it didn't occur to me to use that as a how-to-use-the-map section.

**Comment by rhewitt22** [comment] 2016-08-02 20:36
Duplicate of #5 (moving the discussion there for continuity)

**Closed by rhewitt22** 2016-08-02 20:36 UTC
